feat: added BigBlueButton bbb icon in repo
openedx/paragon pull request #1414
Opened 2022-06-23 14:24 UTC by mehaknasir

## Description

Added big blue button svg icon to utilize it in different MFEs as required. 
A related ticket is [inf-207](https://2u-internal.atlassian.net/browse/INF-207)
Figma link  from where svg is exported : https://www.figma.com/file/SeNpRff5HxzdpCgoD5pmlQ/Apps-and-resources-landing-page?node-id=6598%3A80282

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [ ] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [ ] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [ ] Were your changes tested in the `example` app?
* [ ] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2022-06-23 16:18 UTC, asadazam93 approved these changes

2022-06-24 03:40 UTC, adamstankiewicz requested changes
I believe it might be missing an export of `Bbb` from `icons/es5/index.js`, as the new icon is not appearing on the PR deploy preview: https://deploy-preview-1414--paragon-openedx.netlify.app/foundations/icons

2022-06-24 08:01 UTC, mehaknasir commented
> I believe it might be missing an export of `Bbb` from `icons/es5/index.js`, as the new icon is not appearing on the PR deploy preview: https://deploy-preview-1414--paragon-openedx.netlify.app/foundations/icons

Thanks for the review @adamstankiewicz , I have fixed this thing can you please approve changes now

2022-06-24 09:17 UTC, awais-ansari approved these changes

2022-06-24 10:29 UTC, adamstankiewicz approved these changes
LGTM ✅ :shipit:

2022-06-24 17:03 UTC, merged