[BD-46] is-mutted props for card
openedx/paragon pull request #1455
Opened 2022-07-08 10:33 UTC by Inferato

## Description
is-mutted props for Card component were added 

Github issue: https://github.com/openedx/paragon/issues/1376
### Deploy Preview

https://deploy-preview-1455--paragon-openedx.netlify.app/components/card/

## Merge Checklist

* [x] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [x] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [x] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [x] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [x] Were your changes tested in the `example` app?
* [x] Is there adequate test coverage for your changes?
* [x] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2022-07-08 10:33 UTC, openedx-webhooks commented
Thanks for the pull request, @Inferato!


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-07-15 11:58 UTC, adamstankiewicz requested changes
@Inferato The `Card.Section` component already accepts a `muted` prop to have this styling, e.g.:

```jsx
<Card>
  <Card.Section muted>
    This is a card section. It can contain anything but usually text, a list, or list of links. Multiple sections have a card divider between them.
  </Card.Section>
</Card>
```

This issue was largely to provide an example of what a standalone muted `Card.Section` looks like, not introducing a `muted` prop on the top-level `Card` itself; I should have been more explicit in the issue description, my bad!

We do show an example `Card.Section` with `muted` [already ](https://paragon-openedx.netlify.app/components/card/#section) but I think I'd like to see the `muted` example as the only `Card.Section` inside of the `Card` so the resulting effect is a card completely filled with the muted, light gray background.

2022-07-15 13:17 UTC, adamstankiewicz commented
> @Inferato The `Card.Section` component already accepts a `muted` prop to have this styling, e.g.:
> 
> ```js
> <Card>
>   <Card.Section muted>
>     This is a card section. It can contain anything but usually text, a list, or list of links. Multiple sections have a card divider between them.
>   </Card.Section>
> </Card>
> ```
> 
> This issue was largely to provide an example of what a standalone muted `Card.Section` looks like, not introducing a `muted` prop on the top-level `Card` itself; I should have been more explicit in the issue description, my bad!
> 
> We do show an example `Card.Section` with `muted` [already ](https://paragon-openedx.netlify.app/components/card/#section) but I think I'd like to see the `muted` example as the only `Card.Section` inside of the `Card` so the resulting effect is a card completely filled with the muted, light gray background.

Ignore this. After clarifying with UX during the RG sync, we decided to continue to work with a full muted.

2022-07-29 10:36 UTC, adamstankiewicz approved these changes

2022-07-29 10:36 UTC, merged

2022-07-29 10:36 UTC, openedx-webhooks commented
@Inferato 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1455&entry.1484655318=https://github.com/Inferato&entry.752974735=2022-07-08+10:33&entry.1917517419=2022-07-29+10:36&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2022-07-29 10:51 UTC, edx-semantic-release commented
:tada: This PR is included in version 20.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/paragon/v/20.6.0)
- [GitHub release](https://github.com/openedx/paragon/releases/tag/v20.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: