feat: added new webBlack icon in es5 and js
openedx/paragon pull request #2952
Opened 2023-12-19 11:48 UTC by sundasnoreen12

[INF-1184](https://2u-internal.atlassian.net/browse/INF-1184)

**Description**
Added new webBlack icon in es5 and jsx folders of icon in paragon

2023-12-19 20:38 UTC, brian-smith-tcril requested changes
I don't see an svg file added to [`icons/svg`](https://github.com/openedx/paragon/tree/master/icons/svg) as a part of this PR, which means this icon would disappear the next time someone runs `npm run build` for icons as per [the icons readme](https://github.com/openedx/paragon/tree/master/icons#readme).

2023-12-21 07:36 UTC, sundasnoreen12 commented
> I don't see an svg file added to [`icons/svg`](https://github.com/openedx/paragon/tree/master/icons/svg) as a part of this PR, which means this icon would disappear the next time someone runs `npm run build` for icons as per [the icons readme](https://github.com/openedx/paragon/tree/master/icons#readme).

@brian-smith-tcril I have added svgs. Please review now.

2023-12-21 15:17 UTC, brian-smith-tcril approved these changes
LGTM!

Running `npm run build` in the `icons` dir on this branch works as expected (output matches commit), and everything looks good on the docsite!

![image](https://github.com/openedx/paragon/assets/112954497/be12a7e3-52d2-4672-baca-27015c3fc950)

2023-12-22 08:40 UTC, viktorrusakov approved these changes

2023-12-22 08:41 UTC, merged